name: "deploy"

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Copiar arquivos via SSH"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FLOATBANK_HOST }}
          username: ${{ secrets.FLOATBANK_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/floatingbloodbank"

      - name: "Deploy da Aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FLOATBANK_HOST }}
          username: ${{ secrets.FLOATBANK_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /floatingbloodbank

            # Criar .env com as secrets
            cat > .env << EOL
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            EOL

            # Subir containers
            docker compose down
            docker compose up -d
