name: "deploy"

on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v4
      - name: Debug HOST variable
        run: echo "Host: ${{ secrets.FLOATBACK_HOST }}"
      
      
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FLOATBACK_HOST }}
          username: ${{ secrets.FLOATBACK_USERNAME }}
          key: |
             ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/floatingbloodbank"

      - name: "Deploy Application"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.FLOATBACK_HOST }}
          username: ${{ secrets.FLOATBACK_USERNAME }}
          key: |
                ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            cd /floatingbloodbank
            sudo chown -R jan:users /floatingbloodbank
            sudo chmod -R 775 /floatingbloodbank
            docker compose down
            docker compose up -d --build
            docker compose exec -T app composer install --no-dev --no-progress -a
            docker compose exec -T app php artisan optimize
            docker compose exec -T app npm install

          
 